spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/gestion_p?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
    port: 9999 
